/*
 **************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.2   2017-05-20

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 **************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */



void InitializeTimer(int period = 500){
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);

	TIM_TimeBaseInitTypeDef timerInitStructure;
	timerInitStructure.TIM_Prescaler = 400;
	timerInitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	timerInitStructure.TIM_Period = period;
	timerInitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	timerInitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM4, &timerInitStructure);
	TIM_Cmd(TIM4, ENABLE);
}

void InitializePWMChannel3(int dutycicle = 500){

	TIM_OCInitTypeDef outputChannelInit = {0,};
	outputChannelInit.TIM_OCMode = TIM_OCMode_PWM1;
	outputChannelInit.TIM_Pulse = dutycicle;
	outputChannelInit.TIM_OutputState = TIM_OutputState_Enable;
	outputChannelInit.TIM_OCPolarity = TIM_OCPolarity_High;

	TIM_OC3Init(TIM4, &outputChannelInit);
	TIM_OC3PreloadConfig(TIM4, TIM_OCPreload_Enable);

	GPIO_PinAFConfig(GPIOD, GPIO_PinSource14, GPIO_AF_TIM4);

}


void InitializePWMChannel2(int dutycicle = 500){

	TIM_OCInitTypeDef outputChannelInit = {0,};
	outputChannelInit.TIM_OCMode = TIM_OCMode_PWM1;
	outputChannelInit.TIM_Pulse = dutycicle;
	outputChannelInit.TIM_OutputState = TIM_OutputState_Enable;
	outputChannelInit.TIM_OCPolarity = TIM_OCPolarity_High;

	TIM_OC2Init(TIM4, &outputChannelInit);
	TIM_OC2PreloadConfig(TIM4, TIM_OCPreload_Enable);

	GPIO_PinAFConfig(GPIOD, GPIO_PinSource13, GPIO_AF_TIM4);

}



/*void InitializeLEDs(){
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);

	GPIO_InitTypeDef gpioStructure;
	gpioStructure.GPIO_Pin = GPIO_Pin_14;
	gpioStructure.GPIO_Mode = GPIO_Mode_AF;
	gpioStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_Init(GPIOD, &gpioStructure);
}*/


int SpeedControl(int g, int k){
	//calculando o duty cicle do pwm proporcionalmente a inclinação
	int speed;
	speed = 500-g*k;
	return speed;

}

#define ACCEL_MAX 32766

	int k = 35,speed;
	float gravity,accelx,accelz,accely;
	int g;

	void SysTick_Handler() {
		int contador;
		if (contador != 0) { contador--; }
	}
	// Delay de 1us
	void Delay_us(uint32_t mSecs) {
		uint32_t contador;
		contador = mSecs+1;
		while (contador != 0);
	}

int time;

//uint32_t contador;

int main(void)
{
	 STM_EVAL_LEDInit(LED3);
	  STM_EVAL_LEDInit(LED4);
	  STM_EVAL_LEDInit(LED5);
	  STM_EVAL_LEDInit(LED6);

	SysTick_Config(168-1);
	//InitializeLEDs();
	InitializeTimer(3);
	InitializePWMChannel2(312);

	int laststate;
	int distancia;
	while(1){

	time = 0;
	uint8_t laststate = Bit_SET;
	while(laststate == Bit_SET) {
			laststate = GPIO_ReadInputDataBit(GPIOD, GPIO_Pin_12);
			Delay_us(1);
	                time++;
		}

	distancia=time*0,034/2;

	if (distancia < 0) {
					  	  	  STM_EVAL_LEDOn(LED3);
					  	  	  STM_EVAL_LEDOff(LED4);
				          } else if (distancia > 50) {
				              /* Distance more than 50cm */
				        	  STM_EVAL_LEDOn(LED4);
				        	  STM_EVAL_LEDOff(LED3);

				          } else {
				              /* Distance between 0 and 50cm */
				        	  STM_EVAL_LEDOn(LED5);
				          }



	//InitializeSPI();
	//PonteHcontrol();

	/* Infinite loop */
	//CircularBuffer<uint8_t> buffer(0,1024);




/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
}
}




extern "C" void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
extern "C" uint16_t EVAL_AUDIO_GetSampleCallBack(void){
	/* TODO, implement your code here */
	return -1;
}
